# Project 3: Eliminating Child Care Deserts in New York State through Optimization

In [1]:
#!pip install pulp

In [2]:
import numpy as numpy
import pandas as pd

### Data Cleaning

In [3]:
population = pd.read_csv("https://raw.githubusercontent.com/hayooniverse/IEORE4004-Optimization-Models-and-Methods/refs/heads/main/Project%203/data/population.csv")
employment = pd.read_csv("https://raw.githubusercontent.com/hayooniverse/IEORE4004-Optimization-Models-and-Methods/refs/heads/main/Project%203/data/employment_rate.csv")
income = pd.read_csv("https://raw.githubusercontent.com/hayooniverse/IEORE4004-Optimization-Models-and-Methods/refs/heads/main/Project%203/data/avg_individual_income.csv")
facilities = pd.read_csv("https://raw.githubusercontent.com/hayooniverse/IEORE4004-Optimization-Models-and-Methods/refs/heads/main/Project%203/data/child_care_regulated.csv")
locations = pd.read_csv("https://raw.githubusercontent.com/hayooniverse/IEORE4004-Optimization-Models-and-Methods/refs/heads/main/Project%203/data/potential_locations.csv")

In [4]:
income.rename(columns={
    "ZIP code" : "zipcode"
}, inplace=True)

#### See Data

In [5]:
population.head()

,zipcode,Total,-5,5-9,10-14,15-19,20-24,25-29,30-34,35-39,40-44,45-49,50-54,55-59,60-64,65-69,70-74,75-79,80-84,85+
0,6390,53,0,1,5,0,6,0,9,18,0,12,2,0,0,0,0,0,0,0
1,10001,27004,744,784,942,1035,2296,3806,3588,2524,1702,1903,1704,1225,1323,933,815,616,488,576
2,10002,76518,2142,3046,3198,2652,4528,6988,6278,5157,4962,4822,4410,6106,4548,4815,4748,2531,2793,2794
3,10003,53877,1440,1034,953,7013,6344,7100,6427,3221,2907,1988,2698,2350,2274,2793,1854,1646,779,1056
4,10004,4579,433,182,161,108,109,601,724,490,241,313,549,279,199,173,2,15,0,0

In [6]:
employment.head()

   zipcode  employment rate
0    10001         0.595097
1    10002         0.520662
2    10003         0.497244
3    10004         0.506661
4    10005         0.665833

In [7]:
income.head()

   zipcode  average income
0    10001   102878.033603
1    10002    59604.041165
2    10003   114273.049645
3    10004   132004.310345
4    10005   121437.713311

In [8]:
facilities.head()

,facility_id,program_type,facility_status,facility_name,city,zip_code,school_district_name,infant_capacity,toddler_capacity,preschool_capacity,school_age_capacity,children_capacity,total_capacity,latitude,longitude
0,2416,FDC,Registration,"Bohrer, Barbara",Clinton,13323,Clinton,0,0,0,2,6,8,NaN,NaN
1,5555,FDC,Registration,"Matey, Sally",Jamestown,14701,Jamestown,0,0,0,2,6,8,NaN,NaN
2,9066,FDC,Registration,"Copeland, Denise",Wappingers Falls,12590,Wappingers,0,0,0,2,6,8,NaN,NaN
3,40163,DCC,License,"Head Start of Rockland, Inc.",Nyack,10960,Nyack,0,10,110,0,0,120,41.089425,-73.920413
4,41016,SACC,Registration,"School's Out, Inc.",Glenmont,12077,Bethlehem,0,0,0,75,0,75,42.607043,-73.788606

In [9]:
locations.head()

   zipcode   latitude  longitude
0      501  40.816376 -73.040796
1      501  40.817455 -73.044202
2      501  40.813873 -73.042182
3      501  40.814152 -73.037265
4      501  40.824673 -73.047431

#### Defining Demographic Information
* r_a: the rate of employment of area a
* e_a: the average income level of area a
* p_t_a : the total number of children ages 2 weeks - 12 years in area a
* p_u_a : the total number of children under 5 (babies and toddlers) in area a

In [10]:
# make a copy of employment rate variable
df = employment.copy()
# merge with income on zipcode 
df = df.merge(income, on="zipcode")
# create new column p_t_a: under 5 years old + 5-9 years old + 10-14 years
df["p_t_a"] = population["-5"] + population["5-9"] + population["10-14"]
# create new column p_u_a: under 5 
df["p_u_a"] = population["-5"]
df.rename(columns={"employment rate":"r_a","average income":"e_a"}, inplace=True)
df

      zipcode       r_a            e_a  p_t_a  p_u_a
0       10001  0.595097  102878.033603      6      0
1       10002  0.520662   59604.041165   2470    744
2       10003  0.497244  114273.049645   8386   2142
3       10004  0.506661  132004.310345   3427   1440
4       10005  0.665833  121437.713311    776    433
...       ...       ...            ...    ...    ...
1370    14767  0.322296   54623.287671     42      0
1371    14770  0.446676   55523.255814     42      0
1372    14772  0.410719   57164.634146   1030    375
1373    14805  0.679739   59375.000000    188     20
1374    14806  0.451373   58762.886598     60     13

[1375 rows x 5 columns]

Flagging high-demand areas (defined as regions where at least 60% of parents are employed or the average income is $60,000 or less per year)

In [11]:
df["high_demand"] = (df["r_a"] >= 0.60) | (df["e_a"] <= 60000)
df

      zipcode       r_a            e_a  p_t_a  p_u_a  high_demand
0       10001  0.595097  102878.033603      6      0        False
1       10002  0.520662   59604.041165   2470    744         True
2       10003  0.497244  114273.049645   8386   2142        False
3       10004  0.506661  132004.310345   3427   1440        False
4       10005  0.665833  121437.713311    776    433         True
...       ...       ...            ...    ...    ...          ...
1370    14767  0.322296   54623.287671     42      0         True
1371    14770  0.446676   55523.255814     42      0         True
1372    14772  0.410719   57164.634146   1030    375         True
1373    14805  0.679739   59375.000000    188     20         True
1374    14806  0.451373   58762.886598     60     13         True

[1375 rows x 6 columns]

#### Defining Operational Information
- n_t_a_j : the total number of existing slots in facility j in area a for all age ranges
- n_u_a_j : the number of existing slots in facility j in area a for child under 5

Assumption: Here, we assumed that infants - preschool accounts for the number of children under 5

In [12]:
# adjust variable name
facilities.rename(columns={"zip_code":"zipcode","total_capacity": "n_t_a_j"}, inplace=True)
# cap for under 5 : infant + toddler + preschool
facilities["n_u_a_j"] = (facilities["infant_capacity"] + facilities["toddler_capacity"] + facilities["preschool_capacity"])
facilities

,facility_id,program_type,facility_status,facility_name,city,zipcode,school_district_name,infant_capacity,toddler_capacity,preschool_capacity,school_age_capacity,children_capacity,n_t_a_j,latitude,longitude,n_u_a_j
0,2416,FDC,Registration,"Bohrer, Barbara",Clinton,13323,Clinton,0,0,0,2,6,8,NaN,NaN,0
1,5555,FDC,Registration,"Matey, Sally",Jamestown,14701,Jamestown,0,0,0,2,6,8,NaN,NaN,0
2,9066,FDC,Registration,"Copeland, Denise",Wappingers Falls,12590,Wappingers,0,0,0,2,6,8,NaN,NaN,0
3,40163,DCC,License,"Head Start of Rockland, Inc.",Nyack,10960,Nyack,0,10,110,0,0,120,41.089425,-73.920413,120
4,41016,SACC,Registration,"School's Out, Inc.",Glenmont,12077,Bethlehem,0,0,0,75,0,75,42.607043,-73.788606,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15599,892735,GFDC,License,LITTLE LILIES GROUP FAMILY DAYCARE LLC.,Bronx,10462,Bronx 11,0,0,0,4,12,16,40.854317,-73.864996,0
15600,897263,GFDC,License,"Cummings, Darlene",Brooklyn,11205,Brooklyn 13,0,0,0,0,10,10,40.696940,-73.977121,0
15601,901966,GFDC,License,"Pascal Genao, Angela",Yonkers,10705,Yonkers,0,0,0,4,12,16,40.910754,-73.893528,0
15602,892455,GFDC,License,"Warnakulasuriya, Sajeeka",Staten Island,10303,Richmond 31,0,0,0,4,12,16,40.628144,-74.156228,0
15603,911779,GFDC,License,Tots R Us Childcare,Jamaica,11436,Queens 27,0,0,0,4,12,16,40.674386,-73.791128,0

Now we group the dataset by the zipcodes, so n_t_a_j becomes n_t_a, and n_u_a_j becomes n_u_a.

In [13]:
temp_facilities = facilities.groupby("zipcode").agg({"n_t_a_j": "sum","n_u_a_j": "sum"}).reset_index()
temp_facilities.rename(columns={"n_t_a_j":"n_t_a","n_u_a_j":"n_u_a"}, inplace=True)
temp_facilities

        zipcode  n_t_a  n_u_a
0         10001    609      0
1         10002   4729     18
2         10003   1995      0
3         10004    263      0
4         10005     39      0
...         ...    ...    ...
1599  148799621      8      0
1600  149011149     16      0
1601  149012216     82     82
1602  149042203     16      0
1603  149051400     74     74

[1604 rows x 3 columns]

In [14]:
df = df.merge(temp_facilities, on="zipcode", how="left")
df["n_t_a"] = df["n_t_a"].fillna(0)
df["n_u_a"] = df["n_u_a"].fillna(0)
df

,zipcode,r_a,e_a,p_t_a,p_u_a,high_demand,n_t_a,n_u_a
0,10001,0.595097,102878.033603,6,0,False,609.0,0.0
1,10002,0.520662,59604.041165,2470,744,True,4729.0,18.0
2,10003,0.497244,114273.049645,8386,2142,False,1995.0,0.0
3,10004,0.506661,132004.310345,3427,1440,False,263.0,0.0
4,10005,0.665833,121437.713311,776,433,True,39.0,0.0
...,...,...,...,...,...,...,...,...
1370,14767,0.322296,54623.287671,42,0,True,16.0,0.0
1371,14770,0.446676,55523.255814,42,0,True,70.0,15.0
1372,14772,0.410719,57164.634146,1030,375,True,108.0,32.0
1373,14805,0.679739,59375.000000,188,20,True,8.0,0.0
1374,14806,0.451373,58762.886598,60,13,True,16.0,0.0

#### 1. Child Care Desert Classification
- In high-demand areas: if the number of available slots is less than or equal to half the population of children aged two weeks to 12 years
- In normal-demand areas: if the available slots are less than or equal to one-third of the population of children within the same age range

In [15]:
df["is_desert"] = df.apply(lambda row: row["n_t_a"] <= 0.5 * row["p_t_a"] if row["high_demand"] else row["n_t_a"] <= (1/3) * row["p_t_a"],axis=1)
df

,zipcode,r_a,e_a,p_t_a,p_u_a,high_demand,n_t_a,n_u_a,is_desert
0,10001,0.595097,102878.033603,6,0,False,609.0,0.0,False
1,10002,0.520662,59604.041165,2470,744,True,4729.0,18.0,False
2,10003,0.497244,114273.049645,8386,2142,False,1995.0,0.0,True
3,10004,0.506661,132004.310345,3427,1440,False,263.0,0.0,True
4,10005,0.665833,121437.713311,776,433,True,39.0,0.0,True
...,...,...,...,...,...,...,...,...,...
1370,14767,0.322296,54623.287671,42,0,True,16.0,0.0,True
1371,14770,0.446676,55523.255814,42,0,True,70.0,15.0,False
1372,14772,0.410719,57164.634146,1030,375,True,108.0,32.0,True
1373,14805,0.679739,59375.000000,188,20,True,8.0,0.0,True
1374,14806,0.451373,58762.886598,60,13,True,16.0,0.0,True

#### 2. Age 0-5 Child Care Desert Classification
* Children under the age of 5 must have sufficient access to care
* The number of available slots for children in this age group must be at least two-thirds of the population of children aged 0-5

In [16]:
# n_u_a is the number of existing slots for child under 5
# p_u_a is the number of children under 5 
df["is_under5_desert"] = df["n_u_a"] < (2/3) * df["p_u_a"]
df

,zipcode,r_a,e_a,p_t_a,p_u_a,high_demand,n_t_a,n_u_a,is_desert,is_under5_desert
0,10001,0.595097,102878.033603,6,0,False,609.0,0.0,False,False
1,10002,0.520662,59604.041165,2470,744,True,4729.0,18.0,False,True
2,10003,0.497244,114273.049645,8386,2142,False,1995.0,0.0,True,True
3,10004,0.506661,132004.310345,3427,1440,False,263.0,0.0,True,True
4,10005,0.665833,121437.713311,776,433,True,39.0,0.0,True,True
...,...,...,...,...,...,...,...,...,...,...
1370,14767,0.322296,54623.287671,42,0,True,16.0,0.0,True,False
1371,14770,0.446676,55523.255814,42,0,True,70.0,15.0,False,False
1372,14772,0.410719,57164.634146,1030,375,True,108.0,32.0,True,True
1373,14805,0.679739,59375.000000,188,20,True,8.0,0.0,True,True
1374,14806,0.451373,58762.886598,60,13,True,16.0,0.0,True,True

## Problem A: Budgeting
Determining the minimum amount of funding (in total) needed to meet their target for each area, categorized by zip code

#### Further Clean Facilities Data

In [17]:
facilities = pd.read_csv("https://raw.githubusercontent.com/hayooniverse/IEORE4004-Optimization-Models-and-Methods/refs/heads/main/Project%203/data/child_care_regulated.csv")
facilities["under_5_capacity"] = (facilities["infant_capacity"].fillna(0) + facilities["toddler_capacity"].fillna(0) + facilities["preschool_capacity"].fillna(0))
facilities

,facility_id,program_type,facility_status,facility_name,city,zip_code,school_district_name,infant_capacity,toddler_capacity,preschool_capacity,school_age_capacity,children_capacity,total_capacity,latitude,longitude,under_5_capacity
0,2416,FDC,Registration,"Bohrer, Barbara",Clinton,13323,Clinton,0,0,0,2,6,8,NaN,NaN,0
1,5555,FDC,Registration,"Matey, Sally",Jamestown,14701,Jamestown,0,0,0,2,6,8,NaN,NaN,0
2,9066,FDC,Registration,"Copeland, Denise",Wappingers Falls,12590,Wappingers,0,0,0,2,6,8,NaN,NaN,0
3,40163,DCC,License,"Head Start of Rockland, Inc.",Nyack,10960,Nyack,0,10,110,0,0,120,41.089425,-73.920413,120
4,41016,SACC,Registration,"School's Out, Inc.",Glenmont,12077,Bethlehem,0,0,0,75,0,75,42.607043,-73.788606,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15599,892735,GFDC,License,LITTLE LILIES GROUP FAMILY DAYCARE LLC.,Bronx,10462,Bronx 11,0,0,0,4,12,16,40.854317,-73.864996,0
15600,897263,GFDC,License,"Cummings, Darlene",Brooklyn,11205,Brooklyn 13,0,0,0,0,10,10,40.696940,-73.977121,0
15601,901966,GFDC,License,"Pascal Genao, Angela",Yonkers,10705,Yonkers,0,0,0,4,12,16,40.910754,-73.893528,0
15602,892455,GFDC,License,"Warnakulasuriya, Sajeeka",Staten Island,10303,Richmond 31,0,0,0,4,12,16,40.628144,-74.156228,0
15603,911779,GFDC,License,Tots R Us Childcare,Jamaica,11436,Queens 27,0,0,0,4,12,16,40.674386,-73.791128,0

In [18]:
facilities_dict = {}
for _,row in facilities.iterrows():
    zipcode = row["zip_code"]
    facility_info = (int(row["facility_id"]), int(row["total_capacity"]), int(row["under_5_capacity"]))
    if zipcode not in facilities_dict:
        facilities_dict[zipcode] = []
    facilities_dict[zipcode].append(facility_info)

### Objective
The objective of Problem A is to determine the minimum amount of funding (in total) needed to meet the NYS government's target for each area, categorized by zip code.

The government plans to either:
1. build new child care facilities
2. expand exisiting ones

For this problem, we decided to use the PuLP library.
We referred to this page to learn more about the PuLP library.
https://www.geeksforgeeks.org/python-linear-programming-in-pulp/

#### Create a LP Minimization Problem

In [19]:
import pulp as p
# create minimization problem
model = p.LpProblem("Child_Care_Desert_Elimination", p.LpMinimize)

#### Define Costs
1. Small: Facility Size = 100, # of Slots (Ages 0-5) = 50, Cost of New Facility = 65000
2. Medium: Facility Size = 200, # of Slots (Ages 0-5) = 100, Cost of New Facility = 95000
3. Large: Facility Size = 400, # of Slots (Ages 0-5) = 200, Cost of New Facility = 115,000

In [20]:
new_facility_total_slots = {1: 100, 2: 200, 3: 400}
new_facility_under5_slots = {1: 50, 2: 100, 3: 200}
new_facility_cost = {1: 65000, 2: 95000, 3: 115000}

#### Create Decision Variables
- y_a_i : the number of new facility of type i to build in area a
- x_a_j : the ratio of extended slots over the current slots in facility j in area a
- m_t_a_j : the total number of extended slots for children in facility j in area a
- m_u_a_j : the number of extended slots for children ages 0-5 in facility j in area a
- b_a_j: whether the facility j in area a is expanded (=1 if expanded and 0 otherwise)

In [21]:
# load zipcode to list 
zipcodes = df["zipcode"].tolist()
# load facilities to list 
facility_id = facilities['facility_id']

In [22]:
# create y_a_i
y = {(a, i): p.LpVariable(f"y_{a}_{i}", lowBound=0, cat=p.LpInteger)
     for a in zipcodes for i in [1, 2, 3]}

In [23]:
y

{(10001, 1): y_10001_1,
 (10001, 2): y_10001_2,
 (10001, 3): y_10001_3,
 (10002, 1): y_10002_1,
 (10002, 2): y_10002_2,
 (10002, 3): y_10002_3,
 (10003, 1): y_10003_1,
 (10003, 2): y_10003_2,
 (10003, 3): y_10003_3,
 (10004, 1): y_10004_1,
 (10004, 2): y_10004_2,
 (10004, 3): y_10004_3,
 (10005, 1): y_10005_1,
 (10005, 2): y_10005_2,
 (10005, 3): y_10005_3,
 (10006, 1): y_10006_1,
 (10006, 2): y_10006_2,
 (10006, 3): y_10006_3,
 (10007, 1): y_10007_1,
 (10007, 2): y_10007_2,
 (10007, 3): y_10007_3,
 (10009, 1): y_10009_1,
 (10009, 2): y_10009_2,
 (10009, 3): y_10009_3,
 (10010, 1): y_10010_1,
 (10010, 2): y_10010_2,
 (10010, 3): y_10010_3,
 (10011, 1): y_10011_1,
 (10011, 2): y_10011_2,
 (10011, 3): y_10011_3,
 (10012, 1): y_10012_1,
 (10012, 2): y_10012_2,
 (10012, 3): y_10012_3,
 (10013, 1): y_10013_1,
 (10013, 2): y_10013_2,
 (10013, 3): y_10013_3,
 (10014, 1): y_10014_1,
 (10014, 2): y_10014_2,
 (10014, 3): y_10014_3,
 (10016, 1): y_10016_1,
 (10016, 2): y_10016_2,
 (10016, 3): y_10016_3,
 (10017, 1): y_10017_1,
 (10017, 2): y_10017_2,
 (10017, 3): y_10017_3,
 (10018, 1): y_10018_1,
 (10018, 2): y_10018_2,
 (10018, 3): y_10018_3,
 (10019, 1): y_10019_1,
 (10019, 2): y_10019_2,
 (10019, 3): y_10019_3,
 (10021, 1): y_10021_1,
 (10021, 2): y_10021_2,
 (10021, 3): y_10021_3,
 (10022, 1): y_10022_1,
 (10022, 2): y_10022_2,
 (10022, 3): y_10022_3,
 (10023, 1): y_10023_1,
 (10023, 2): y_10023_2,
 (10023, 3): y_10023_3,
 (10024, 1): y_10024_1,
 (10024, 2): y_10024_2,
 (10024, 3): y_10024_3,
 (10025, 1): y_10025_1,
 (10025, 2): y_10025_2,
 (10025, 3): y_10025_3,
 (10026, 1): y_10026_1,
 (10026, 2): y_10026_2,
 (10026, 3): y_10026_3,
 (10027, 1): y_10027_1,
 (10027, 2): y_10027_2,
 (10027, 3): y_10027_3,
 (10028, 1): y_10028_1,
 (10028, 2): y_10028_2,
 (10028, 3): y_10028_3,
 (10029, 1): y_10029_1,
 (10029, 2): y_10029_2,
 (10029, 3): y_10029_3,
 (10030, 1): y_10030_1,
 (10030, 2): y_10030_2,
 (10030, 3): y_10030_3,
 (10031, 1): y_10031_1,
 (10031, 2): y_10031_2,
 (10031, 3): y_10031_3,
 (10032, 1): y_10032_1,
 (10032, 2): y_10032_2,
 (10032, 3): y_10032_3,
 (10033, 1): y_10033_1,
 (10033, 2): y_10033_2,
 (10033, 3): y_10033_3,
 (10034, 1): y_10034_1,
 (10034, 2): y_10034_2,
 (10034, 3): y_10034_3,
 (10035, 1): y_10035_1,
 (10035, 2): y_10035_2,
 (10035, 3): y_10035_3,
 (10036, 1): y_10036_1,
 (10036, 2): y_10036_2,
 (10036, 3): y_10036_3,
 (10037, 1): y_10037_1,
 (10037, 2): y_10037_2,
 (10037, 3): y_10037_3,
 (10038, 1): y_10038_1,
 (10038, 2): y_10038_2,
 (10038, 3): y_10038_3,
 (10039, 1): y_10039_1,
 (10039, 2): y_10039_2,
 (10039, 3): y_10039_3,
 (10040, 1): y_10040_1,
 (10040, 2): y_10040_2,
 (10040, 3): y_10040_3,
 (10044, 1): y_10044_1,
 (10044, 2): y_10044_2,
 (10044, 3): y_10044_3,
 (10065, 1): y_10065_1,
 (10065, 2): y_10065_2,
 (10065, 3): y_10065_3,
 (10069, 1): y_10069_1,
 (10069, 2): y_10069_2,
 (10069, 3): y_10069_3,
 (10075, 1): y_10075_1,
 (10075, 2): y_10075_2,
 (10075, 3): y_10075_3,
 (10128, 1): y_10128_1,
 (10128, 2): y_10128_2,
 (10128, 3): y_10128_3,
 (10162, 1): y_10162_1,
 (10162, 2): y_10162_2,
 (10162, 3): y_10162_3,
 (10280, 1): y_10280_1,
 (10280, 2): y_10280_2,
 (10280, 3): y_10280_3,
 (10282, 1): y_10282_1,
 (10282, 2): y_10282_2,
 (10282, 3): y_10282_3,
 (10301, 1): y_10301_1,
 (10301, 2): y_10301_2,
 (10301, 3): y_10301_3,
 (10302, 1): y_10302_1,
 (10302, 2): y_10302_2,
 (10302, 3): y_10302_3,
 (10303, 1): y_10303_1,
 (10303, 2): y_10303_2,
 (10303, 3): y_10303_3,
 (10304, 1): y_10304_1,
 (10304, 2): y_10304_2,
 (10304, 3): y_10304_3,
 (10305, 1): y_10305_1,
 (10305, 2): y_10305_2,
 (10305, 3): y_10305_3,
 (10306, 1): y_10306_1,
 (10306, 2): y_10306_2,
 (10306, 3): y_10306_3,
 (10307, 1): y_10307_1,
 (10307, 2): y_10307_2,
 (10307, 3): y_10307_3,
 (10308, 1): y_10308_1,
 (10308, 2): y_10308_2,
 (10308, 3): y_10308_3,
 (10309, 1): y_10309_1,
 (10309, 2): y_10309_2,
 (10309, 3): y_10309_3,
 (10310, 1): y_10310_1,
 (10310, 2): y_10310_2,
 (10310, 3): y_10310_3,
 (10312, 1): y_10312_1,
 (10312, 2): y_10312_2,
 (10312, 3): y_10312_3,
 (10314, 1): y_10314_1,
 (10314, 2): y_10314_2,
 (10314, 3): y_10314_3,
 (10451, 1): y_10451_1,
 (10451, 2): y_10451_2,
 (10451, 3): y_10451_3,
 (10452, 1): y_10452_1,
 (10452, 2): y_10452_2,
 (10452, 3): y_10452_3,
 (10453, 1): y_10453_1,
 (10453, 2): y_10453_2,
 (10453, 3): y_10453_3,
 (10454, 1): y_10454_1,
 (10454, 2): y_10454_2,
 (10454, 3): y_10454_3,
 (10455, 1): y_10455_1,
 (10455, 2): y_10455_2,
 (10455, 3): y_10455_3,
 (10456, 1): y_10456_1,
 (10456, 2): y_10456_2,
 (10456, 3): y_10456_3,
 (10457, 1): y_10457_1,
 (10457, 2): y_10457_2,
 (10457, 3): y_10457_3,
 (10458, 1): y_10458_1,
 (10458, 2): y_10458_2,
 (10458, 3): y_10458_3,
 (10459, 1): y_10459_1,
 (10459, 2): y_10459_2,
 (10459, 3): y_10459_3,
 (10460, 1): y_10460_1,
 (10460, 2): y_10460_2,
 (10460, 3): y_10460_3,
 (10461, 1): y_10461_1,
 (10461, 2): y_10461_2,
 (10461, 3): y_10461_3,
 (10462, 1): y_10462_1,
 (10462, 2): y_10462_2,
 (10462, 3): y_10462_3,
 (10463, 1): y_10463_1,
 (10463, 2): y_10463_2,
 (10463, 3): y_10463_3,
 (10464, 1): y_10464_1,
 (10464, 2): y_10464_2,
 (10464, 3): y_10464_3,
 (10465, 1): y_10465_1,
 (10465, 2): y_10465_2,
 (10465, 3): y_10465_3,
 (10466, 1): y_10466_1,
 (10466, 2): y_10466_2,
 (10466, 3): y_10466_3,
 (10467, 1): y_10467_1,
 (10467, 2): y_10467_2,
 (10467, 3): y_10467_3,
 (10468, 1): y_10468_1,
 (10468, 2): y_10468_2,
 (10468, 3): y_10468_3,
 (10469, 1): y_10469_1,
 (10469, 2): y_10469_2,
 (10469, 3): y_10469_3,
 (10470, 1): y_10470_1,
 (10470, 2): y_10470_2,
 (10470, 3): y_10470_3,
 (10471, 1): y_10471_1,
 (10471, 2): y_10471_2,
 (10471, 3): y_10471_3,
 (10472, 1): y_10472_1,
 (10472, 2): y_10472_2,
 (10472, 3): y_10472_3,
 (10473, 1): y_10473_1,
 (10473, 2): y_10473_2,
 (10473, 3): y_10473_3,
 (10474, 1): y_10474_1,
 (10474, 2): y_10474_2,
 (10474, 3): y_10474_3,
 (10475, 1): y_10475_1,
 (10475, 2): y_10475_2,
 (10475, 3): y_10475_3,
 (10501, 1): y_10501_1,
 (10501, 2): y_10501_2,
 (10501, 3): y_10501_3,
 (10502, 1): y_10502_1,
 (10502, 2): y_10502_2,
 (10502, 3): y_10502_3,
 (10504, 1): y_10504_1,
 (10504, 2): y_10504_2,
 (10504, 3): y_10504_3,
 (10505, 1): y_10505_1,
 (10505, 2): y_10505_2,
 (10505, 3): y_10505_3,
 (10506, 1): y_10506_1,
 (10506, 2): y_10506_2,
 (10506, 3): y_10506_3,
 (10507, 1): y_10507_1,
 (10507, 2): y_10507_2,
 (10507, 3): y_10507_3,
 (10509, 1): y_10509_1,
 (10509, 2): y_10509_2,
 (10509, 3): y_10509_3,
 (10510, 1): y_10510_1,
 (10510, 2): y_10510_2,
 (10510, 3): y_10510_3,
 (10511, 1): y_10511_1,
 (10511, 2): y_10511_2,
 (10511, 3): y_10511_3,
 (10512, 1): y_10512_1,
 (10512, 2): y_10512_2,
 (10512, 3): y_10512_3,
 (10514, 1): y_10514_1,
 (10514, 2): y_10514_2,
 (10514, 3): y_10514_3,
 (10516, 1): y_10516_1,
 (10516, 2): y_10516_2,
 (10516, 3): y_10516_3,
 (10518, 1): y_10518_1,
 (10518, 2): y_10518_2,
 (10518, 3): y_10518_3,
 (10520, 1): y_10520_1,
 (10520, 2): y_10520_2,
 (10520, 3): y_10520_3,
 (10522, 1): y_10522_1,
 (10522, 2): y_10522_2,
 (10522, 3): y_10522_3,
 (10523, 1): y_10523_1,
 (10523, 2): y_10523_2,
 (10523, 3): y_10523_3,
 (10524, 1): y_10524_1,
 (10524, 2): y_10524_2,
 (10524, 3): y_10524_3,
 (10526, 1): y_10526_1,
 (10526, 2): y_10526_2,
 (10526, 3): y_10526_3,
 (10527, 1): y_10527_1,
 (10527, 2): y_10527_2,
 (10527, 3): y_10527_3,
 (10528, 1): y_10528_1,
 (10528, 2): y_10528_2,
 (10528, 3): y_10528_3,
 (10530, 1): y_10530_1,
 (10530, 2): y_10530_2,
 (10530, 3): y_10530_3,
 (10532, 1): y_10532_1,
 (10532, 2): y_10532_2,
 (10532, 3): y_10532_3,
 (10533, 1): y_10533_1,
 (10533, 2): y_10533_2,
 (10533, 3): y_10533_3,
 (10535, 1): y_10535_1,
 (10535, 2): y_10535_2,
 (10535, 3): y_10535_3,
 (10536, 1): y_10536_1,
 (10536, 2): y_10536_2,
 (10536, 3): y_10536_3,
 (10537, 1): y_10537_1,
 (10537, 2): y_10537_2,
 (10537, 3): y_10537_3,
 (10538, 1): y_10538_1,
 (10538, 2): y_10538_2,
 (10538, 3): y_10538_3,
 (10541, 1): y_10541_1,
 (10541, 2): y_10541_2,
 (10541, 3): y_10541_3,
 (10543, 1): y_10543_1,
 (10543, 2): y_10543_2,
 (10543, 3): y_10543_3,
 (10546, 1): y_10546_1,
 (10546, 2): y_10546_2,
 (10546, 3): y_10546_3,
 (10547, 1): y_10547_1,
 (10547, 2): y_10547_2,
 (10547, 3): y_10547_3,
 (10548, 1): y_10548_1,
 (10548, 2): y_10548_2,
 (10548, 3): y_10548_3,
 (10549, 1): y_10549_1,
 (10549, 2): y_10549_2,
 (10549, 3): y_10549_3,
 (10550, 1): y_10550_1,
 (10550, 2): y_10550_2,
 (10550, 3): y_10550_3,
 (10552, 1): y_10552_1,
 (10552, 2): y_10552_2,
 (10552, 3): y_10552_3,
 (10553, 1): y_10553_1,
 (10553, 2): y_10553_2,
 (10553, 3): y_10553_3,
 (10560, 1): y_10560_1,
 (10560, 2): y_10560_2,
 (10560, 3): y_10560_3,
 (10562, 1): y_10562_1,
 (10562, 2): y_10562_2,
 (10562, 3): y_10562_3,
 (10566, 1): y_10566_1,
 (10566, 2): y_10566_2,
 (10566, 3): y_10566_3,
 (10567, 1): y_10567_1,
 (10567, 2): y_10567_2,
 (10567, 3): y_10567_3,
 (10570, 1): y_10570_1,
 (10570, 2): y_10570_2,
 (10570, 3): y_10570_3,
 (10573, 1): y_10573_1,
 (10573, 2): y_10573_2,
 (10573, 3): y_10573_3,
 (10576, 1): y_10576_1,
 (10576, 2): y_10576_2,
 (10576, 3): y_10576_3,
 (10577, 1): y_10577_1,
 (10577, 2): y_10577_2,
 (10577, 3): y_10577_3,
 (10578, 1): y_10578_1,
 (10578, 2): y_10578_2,
 (10578, 3): y_10578_3,
 (10579, 1): y_10579_1,
 (10579, 2): y_10579_2,
 (10579, 3): y_10579_3,
 (10580, 1): y_10580_1,
 (10580, 2): y_10580_2,
 (10580, 3): y_10580_3,
 (10583, 1): y_10583_1,
 (10583, 2): y_10583_2,
 (10583, 3): y_10583_3,
 (10588, 1): y_10588_1,
 (10588, 2): y_10588_2,
 (10588, 3): y_10588_3,
 (10589, 1): y_10589_1,
 (10589, 2): y_10589_2,
 (10589, 3): y_10589_3,
 (10590, 1): y_10590_1,
 (10590, 2): y_10590_2,
 (10590, 3): y_10590_3,
 (10591, 1): y_10591_1,
 (10591, 2): y_10591_2,
 (10591, 3): y_10591_3,
 (10594, 1): y_10594_1,
 (10594, 2): y_10594_2,
 (10594, 3): y_10594_3,
 (10595, 1): y_10595_1,
 (10595, 2): y_10595_2,
 (10595, 3): y_10595_3,
 (10597, 1): y_10597_1,
 (10597, 2): y_10597_2,
 (10597, 3): y_10597_3,
 (10598, 1): y_10598_1,
 (10598, 2): y_10598_2,
 (10598, 3): y_10598_3,
 (10601, 1): y_10601_1,
 (10601, 2): y_10601_2,
 (10601, 3): y_10601_3,
 (10603, 1): y_10603_1,
 (10603, 2): y_10603_2,
 (10603, 3): y_10603_3,
 (10604, 1): y_10604_1,
 (10604, 2): y_10604_2,
 (10604, 3): y_10604_3,
 (10605, 1): y_10605_1,
 (10605, 2): y_10605_2,
 (10605, 3): y_10605_3,
 (10606, 1): y_10606_1,
 (10606, 2): y_10606_2,
 (10606, 3): y_10606_3,
 (10607, 1): y_10607_1,
 (10607, 2): y_10607_2,
 (10607, 3): y_10607_3,
 (10701, 1): y_10701_1,
 (10701, 2): y_10701_2,
 (10701, 3): y_10701_3,
 (10703, 1): y_10703_1,
 (10703, 2): y_10703_2,
 (10703, 3): y_10703_3,
 (10704, 1): y_10704_1,
 (10704, 2): y_10704_2,
 (10704, 3): y_10704_3,
 (10705, 1): y_10705_1,
 (10705, 2): y_10705_2,
 (10705, 3): y_10705_3,
 (10706, 1): y_10706_1,
 (10706, 2): y_10706_2,
 (10706, 3): y_10706_3,
 (10707, 1): y_10707_1,
 (10707, 2): y_10707_2,
 (10707, 3): y_10707_3,
 (10708, 1): y_10708_1,
 (10708, 2): y_10708_2,
 (10708, 3): y_10708_3,
 (10709, 1): y_10709_1,
 (10709, 2): y_10709_2,
 (10709, 3): y_10709_3,
 (10710, 1): y_10710_1,
 (10710, 2): y_10710_2,
 (10710, 3): y_10710_3,
 (10801, 1): y_10801_1,
 (10801, 2): y_10801_2,
 (10801, 3): y_10801_3,
 (10803, 1): y_10803_1,
 (10803, 2): y_10803_2,
 (10803, 3): y_10803_3,
 (10804, 1): y_10804_1,
 (10804, 2): y_10804_2,
 (10804, 3): y_10804_3,
 (10805, 1): y_10805_1,
 (10805, 2): y_10805_2,
 (10805, 3): y_10805_3,
 (10901, 1): y_10901_1,
 (10901, 2): y_10901_2,
 (10901, 3): y_10901_3,
 (10913, 1): y_10913_1,
 (10913, 2): y_10913_2,
 (10913, 3): y_10913_3,
 (10916, 1): y_10916_1,
 (10916, 2): y_10916_2,
 (10916, 3): y_10916_3,
 (10917, 1): y_10917_1,
 (10917, 2): y_10917_2,
 (10917, 3): y_10917_3,
 (10918, 1): y_10918_1,
 (10918, 2): y_10918_2,
 (10918, 3): y_10918_3,
 (10919, 1): y_10919_1,
 (10919, 2): y_10919_2,
 (10919, 3): y_10919_3,
 (10920, 1): y_10920_1,
 (10920, 2): y_10920_2,
 (10920, 3): y_10920_3,
 (10921, 1): y_10921_1,
 (10921, 2): y_10921_2,
 (10921, 3): y_10921_3,
 (10923, 1): y_10923_1,
 (10923, 2): y_10923_2,
 (10923, 3): y_10923_3,
 (10924, 1): y_10924_1,
 (10924, 2): y_10924_2,
 (10924, 3): y_10924_3,
 (10925, 1): y_10925_1,
 (10925, 2): y_10925_2,
 (10925, 3): y_10925_3,
 (10926, 1): y_10926_1,
 (10926, 2): y_10926_2,
 (10926, 3): y_10926_3,
 (10927, 1): y_10927_1,
 (10927, 2): y_10927_2,
 (10927, 3): y_10927_3,
 (10928, 1): y_10928_1,
 (10928, 2): y_10928_2,
 (10928, 3): y_10928_3,
 (10930, 1): y_10930_1,
 (10930, 2): y_10930_2,
 (10930, 3): y_10930_3,
 (10940, 1): y_10940_1,
 (10940, 2): y_10940_2,
 (10940, 3): y_10940_3,
 (10941, 1): y_10941_1,
 (10941, 2): y_10941_2,
 (10941, 3): y_10941_3,
 (10950, 1): y_10950_1,
 (10950, 2): y_10950_2,
 (10950, 3): y_10950_3,
 (10952, 1): y_10952_1,
 (10952, 2): y_10952_2,
 (10952, 3): y_10952_3,
 (10954, 1): y_10954_1,
 (10954, 2): y_10954_2,
 (10954, 3): y_10954_3,
 (10956, 1): y_10956_1,
 (10956, 2): y_10956_2,
 (10956, 3): y_10956_3,
 (10958, 1): y_10958_1,
 (10958, 2): y_10958_2,
 (10958, 3): y_10958_3,
 (10960, 1): y_10960_1,
 (10960, 2): y_10960_2,
 (10960, 3): y_10960_3,
 (10962, 1): y_10962_1,
 (10962, 2): y_10962_2,
 (10962, 3): y_10962_3,
 (10963, 1): y_10963_1,
 (10963, 2): y_10963_2,
 (10963, 3): y_10963_3,
 (10964, 1): y_10964_1,
 (10964, 2): y_10964_2,
 (10964, 3): y_10964_3,
 (10965, 1): y_10965_1,
 (10965, 2): y_10965_2,
 (10965, 3): y_10965_3,
 (10968, 1): y_10968_1,
 (10968, 2): y_10968_2,
 (10968, 3): y_10968_3,
 (10969, 1): y_10969_1,
 (10969, 2): y_10969_2,
 (10969, 3): y_10969_3,
 (10970, 1): y_10970_1,
 (10970, 2): y_10970_2,
 (10970, 3): y_10970_3,
 (10973, 1): y_10973_1,
 (10973, 2): y_10973_2,
 (10973, 3): y_10973_3,
 (10974, 1): y_10974_1,
 (10974, 2): y_10974_2,
 (10974, 3): y_10974_3,
 (10975, 1): y_10975_1,
 (10975, 2): y_10975_2,
 (10975, 3): y_10975_3,
 (10976, 1): y_10976_1,
 (10976, 2): y_10976_2,
 (10976, 3): y_10976_3,
 (10977, 1): y_10977_1,
 (10977, 2): y_10977_2,
 (10977, 3): y_10977_3,
 (10980, 1): y_10980_1,
 (10980, 2): y_10980_2,
 (10980, 3): y_10980_3,
 (10983, 1): y_10983_1,
 (10983, 2): y_10983_2,
 (10983, 3): y_10983_3,
 (10984, 1): y_10984_1,
 (10984, 2): y_10984_2,
 (10984, 3): y_10984_3,
 (10985, 1): y_10985_1,
 (10985, 2): y_10985_2,
 (10985, 3): y_10985_3,
 (10986, 1): y_10986_1,
 (10986, 2): y_10986_2,
 (10986, 3): y_10986_3,
 (10987, 1): y_10987_1,
 (10987, 2): y_10987_2,
 (10987, 3): y_10987_3,
 (10989, 1): y_10989_1,
 (10989, 2): y_10989_2,
 (10989, 3): y_10989_3,
 (10990, 1): y_10990_1,
 (10990, 2): y_10990_2,
 (10990, 3): y_10990_3,
 (10992, 1): y_10992_1,
 (10992, 2): y_10992_2,
 (10992, 3): y_10992_3,
 (10993, 1): y_10993_1,
 (10993, 2): y_10993_2,
 (10993, 3): y_10993_3,
 (10994, 1): y_10994_1,
 (10994, 2): y_10994_2,
 (10994, 3): y_10994_3,
 (10996, 1): y_10996_1,
 (10996, 2): y_10996_2,
 (10996, 3): y_10996_3,
 (10998, 1): y_10998_1,
 (10998, 2): y_10998_2,
 (10998, 3): y_10998_3,
 (11001, 1): y_11001_1,
 (11001, 2): y_11001_2,
 (11001, 3): y_11001_3,
 (11003, 1): y_11003_1,
 (11003, 2): y_11003_2,
 (11003, 3): y_11003_3,
 (11004, 1): y_11004_1,
 (11004, 2): y_11004_2,
 (11004, 3): y_11004_3,
 (11005, 1): y_11005_1,
 (11005, 2): y_11005_2,
 (11005, 3): y_11005_3,
 (11010, 1): y_11010_1,
 (11010, 2): y_11010_2,
 (11010, 3): y_11010_3,
 (11020, 1): y_11020_1,
 (11020, 2): y_11020_2,
 (11020, 3): y_11020_3,
 (11021, 1): y_11021_1,
 (11021, 2): y_11021_2,
 (11021, 3): y_11021_3,
 (11023, 1): y_11023_1,
 (11023, 2): y_11023_2,
 (11023, 3): y_11023_3,
 (11024, 1): y_11024_1,
 (11024, 2): y_11024_2,
 (11024, 3): y_11024_3,
 (11030, 1): y_11030_1,
 (11030, 2): y_11030_2,
 (11030, 3): y_11030_3,
 (11040, 1): y_11040_1,
 (11040, 2): y_11040_2,
 (11040, 3): y_11040_3,
 (11042, 1): y_11042_1,
 (11042, 2): y_11042_2,
 (11042, 3): y_11042_3,
 (11050, 1): y_11050_1,
 (11050, 2): y_11050_2,
 (11050, 3): y_11050_3,
 (11096, 1): y_11096_1,
 (11096, 2): y_11096_2,
 (11096, 3): y_11096_3,
 (11101, 1): y_11101_1,
 (11101, 2): y_11101_2,
 (11101, 3): y_11101_3,
 (11102, 1): y_11102_1,
 (11102, 2): y_11102_2,
 (11102, 3): y_11102_3,
 (11103, 1): y_11103_1,
 (11103, 2): y_11103_2,
 (11103, 3): y_11103_3,
 (11104, 1): y_11104_1,
 (11104, 2): y_11104_2,
 (11104, 3): y_11104_3,
 (11105, 1): y_11105_1,
 (11105, 2): y_11105_2,
 (11105, 3): y_11105_3,
 (11106, 1): y_11106_1,
 (11106, 2): y_11106_2,
 (11106, 3): y_11106_3,
 (11109, 1): y_11109_1,
 (11109, 2): y_11109_2,
 (11109, 3): y_11109_3,
 (11201, 1): y_11201_1,
 (11201, 2): y_11201_2,
 (11201, 3): y_11201_3,
 (11203, 1): y_11203_1,
 (11203, 2): y_11203_2,
 (11203, 3): y_11203_3,
 (11204, 1): y_11204_1,
 (11204, 2): y_11204_2,
 (11204, 3): y_11204_3,
 (11205, 1): y_11205_1,
 (11205, 2): y_11205_2,
 (11205, 3): y_11205_3,
 (11206, 1): y_11206_1,
 (11206, 2): y_11206_2,
 (11206, 3): y_11206_3,
 (11207, 1): y_11207_1,
 (11207, 2): y_11207_2,
 (11207, 3): y_11207_3,
 (11208, 1): y_11208_1,
 (11208, 2): y_11208_2,
 (11208, 3): y_11208_3,
 (11209, 1): y_11209_1,
 (11209, 2): y_11209_2,
 (11209, 3): y_11209_3,
 (11210, 1): y_11210_1,
 (11210, 2): y_11210_2,
 (11210, 3): y_11210_3,
 (11211, 1): y_11211_1,
 (11211, 2): y_11211_2,
 (11211, 3): y_11211_3,
 (11212, 1): y_11212_1,
 (11212, 2): y_11212_2,
 (11212, 3): y_11212_3,
 (11213, 1): y_11213_1,
 (11213, 2): y_11213_2,
 (11213, 3): y_11213_3,
 (11214, 1): y_11214_1,
 (11214, 2): y_11214_2,
 (11214, 3): y_11214_3,
 (11215, 1): y_11215_1,
 (11215, 2): y_11215_2,
 (11215, 3): y_11215_3,
 (11216, 1): y_11216_1,
 (11216, 2): y_11216_2,
 (11216, 3): y_11216_3,
 (11217, 1): y_11217_1,
 (11217, 2): y_11217_2,
 (11217, 3): y_11217_3,
 (11218, 1): y_11218_1,
 (11218, 2): y_11218_2,
 (11218, 3): y_11218_3,
 (11219, 1): y_11219_1,
 (11219, 2): y_11219_2,
 (11219, 3): y_11219_3,
 (11220, 1): y_11220_1,
 (11220, 2): y_11220_2,
 (11220, 3): y_11220_3,
 (11221, 1): y_11221_1,
 (11221, 2): y_11221_2,
 (11221, 3): y_11221_3,
 (11222, 1): y_11222_1,
 (11222, 2): y_11222_2,
 (11222, 3): y_11222_3,
 (11223, 1): y_11223_1,
 (11223, 2): y_11223_2,
 (11223, 3): y_11223_3,
 (11224, 1): y_11224_1,
 (11224, 2): y_11224_2,
 (11224, 3): y_11224_3,
 (11225, 1): y_11225_1,
 (11225, 2): y_11225_2,
 (11225, 3): y_11225_3,
 (11226, 1): y_11226_1,
 (11226, 2): y_11226_2,
 (11226, 3): y_11226_3,
 (11228, 1): y_11228_1,
 (11228, 2): y_11228_2,
 (11228, 3): y_11228_3,
 (11229, 1): y_11229_1,
 (11229, 2): y_11229_2,
 (11229, 3): y_11229_3,
 (11230, 1): y_11230_1,
 (11230, 2): y_11230_2,
 (11230, 3): y_11230_3,
 (11231, 1): y_11231_1,
 (11231, 2): y_11231_2,
 (11231, 3): y_11231_3,
 (11232, 1): y_11232_1,
 (11232, 2): y_11232_2,
 (11232, 3): y_11232_3,
 (11233, 1): y_11233_1,
 (11233, 2): y_11233_2,
 (11233, 3): y_11233_3,
 (11234, 1): y_11234_1,
 (11234, 2): y_11234_2,
 (11234, 3): y_11234_3,
 (11235, 1): y_11235_1,
 (11235, 2): y_11235_2,
 (11235, 3): y_11235_3,
 (11236, 1): y_11236_1,
 (11236, 2): y_11236_2,
 (11236, 3): y_11236_3,
 (11237, 1): y_11237_1,
 (11237, 2): y_11237_2,
 (11237, 3): y_11237_3,
 (11238, 1): y_11238_1,
 (11238, 2): y_11238_2,
 (11238, 3): y_11238_3,
 (11239, 1): y_11239_1,
 (11239, 2): y_11239_2,
 (11239, 3): y_11239_3,
 (11354, 1): y_11354_1,
 (11354, 2): y_11354_2,
 (11354, 3): y_11354_3,
 (11355, 1): y_11355_1,
 (11355, 2): y_11355_2,
 (11355, 3): y_11355_3,
 (11356, 1): y_11356_1,
 (11356, 2): y_11356_2,
 (11356, 3): y_11356_3,
 (11357, 1): y_11357_1,
 (11357, 2): y_11357_2,
 (11357, 3): y_11357_3,
 (11358, 1): y_11358_1,
 (11358, 2): y_11358_2,
 (11358, 3): y_11358_3,
 (11360, 1): y_11360_1,
 (11360, 2): y_11360_2,
 (11360, 3): y_11360_3,
 (11361, 1): y_11361_1,
 (11361, 2): y_11361_2,
 (11361, 3): y_11361_3,
 (11362, 1): y_11362_1,
 (11362, 2): y_11362_2,
 (11362, 3): y_11362_3,
 (11363, 1): y_11363_1,
 (11363, 2): y_11363_2,
 (11363, 3): y_11363_3,
 (11364, 1): y_11364_1,
 (11364, 2): y_11364_2,
 (11364, 3): y_11364_3,
 (11365, 1): y_11365_1,
 (11365, 2): y_11365_2,
 (11365, 3): y_11365_3,
 (11366, 1): y_11366_1,
 (11366, 2): y_11366_2,
 (11366, 3): y_11366_3,
 (11367, 1): y_11367_1,
 (11367, 2): y_11367_2,
 (11367, 3): y_11367_3,
 (11368, 1): y_11368_1,
 (11368, 2): y_11368_2,
 (11368, 3): y_11368_3,
 (11369, 1): y_11369_1,
 (11369, 2): y_11369_2,

In [24]:
# create x_a_j
x = {(a, j): p.LpVariable(f"x_{a}_{j}", lowBound=0, upBound =0.2, cat=p.LpContinuous)
     for a in zipcodes for j in facility_id}

In [25]:
# create m_t_a_j
m_t = {(a, j): p.LpVariable(f"m_t_{a}_{j}", lowBound=0, cat=p.LpInteger)
     for a in zipcodes for j in facility_id}

In [26]:
m_u = {(a, j): p.LpVariable(f"m_u_{a}_{j}", lowBound=0, cat=p.LpInteger)
     for a in zipcodes for j in facility_id}

#### Create Objective Function

In [27]:
# Expansion based on size ( less than 10%, 10%-15%, 15%-20%) as given in page 3 
expansion_cost = p.lpSum(
    (20000 + (200 if x[(a, j)] <= 0.1 else 400 if x[(a, j)] <= 0.15 else 1000) * nt) * x[(a, j)]
    # additional cost per slot for children under 5
    + 100 * m_u[(a, j)]
    for a in zipcodes for (j, nt, _) in facilities.get(a, [])
)

In [28]:
# expansion cost + new facility cost (determined by size - small:1, medium:2, large:3)
model += expansion_cost + p.lpSum(y[(a, i)] * new_facility_cost[i] for a in zipcodes for i in [1, 2, 3])

#### Create Constraints

In [29]:
for idx, row in df.iterrows():
    a = row["zipcode"]
    existing_total = row["n_t_a"]
    existing_under5 = row["n_u_a"]
    p_t = row["p_t_a"]
    p_u = row["p_u_a"]
    threshold = 0.5 if row["high_demand"] else (1/3)

    # Total slot coverage
    model += (
        existing_total +
        p.lpSum(m_t[(a, j)] for (j, _, _) in facilities.get(a, [])) +
        p.lpSum(new_facility_total_slots[i] * y[(a, i)] for i in [1, 2, 3])
        >= threshold * p_t
    )

    # Under-5 slot coverage
    model += (
        existing_under5 +
        p.lpSum(m_u[(a, j)] for (j, _, _) in facilities.get(a, [])) +
        p.lpSum(new_facility_under5_slots[i] * y[(a, i)] for i in [1, 2, 3])
        >= (2/3) * p_u
    )

In [30]:
# Expansion constraints
for a in zipcodes:
    for (j, nt, _) in facilities.get(a, []):
        # expansion rate constraint as given: expansion ratio * current 
        model += m_t[(a, j)] == x[(a, j)] * nt
        # under-5 slots can't exceed the total num. of newly added 
        model += m_u[(a, j)] <= m_t[(a, j)]
        # maximum 500 slots per facility
        if nt >= 500:
            model += x[(a, j)] == 0 # force 0 when facility is already 500

In [31]:
# Budget Constraint
budget_limit = 100_000_000  # $100 million
model += (
    expansion_cost +
    p.lpSum(y[(a, i)] * new_facility_cost[i] for a in zipcodes for i in [1, 2, 3])
    <= budget_limit
), "Budget_Constraint"

In [32]:
# Solve Model 
model.solve(p.PULP_CBC_CMD(msg=True)) 
print(f"Status: {p.LpStatus[model.status]}")
print(f"Objective Cost: ${p.value(model.objective):,.2f}")

# Output new facilities to build
build_rows = []
for (a, i), var in y.items():
    if var.varValue and var.varValue > 0:
        build_rows.append({
            "zipcode": a,
            "facility_type": i,
            "num_to_build": int(var.varValue),
            "slots_added": new_facility_total_slots[i] * int(var.varValue),
            "under5_slots_added": new_facility_under5_slots[i] * int(var.varValue),
        })

df_builds = pd.DataFrame(build_rows)

print("New Facilities to Build:")
display(df_builds)

Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pulp/solverdir/cbc/osx/64/cbc /var/folders/pp/n1knqjg57ds10zbbb7v7yvfw0000gn/T/f5d9f0a04a8f4cfa8236b03582ee3d2f-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /var/folders/pp/n1knqjg57ds10zbbb7v7yvfw0000gn/T/f5d9f0a04a8f4cfa8236b03582ee3d2f-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 2756 COLUMNS
At line 27507 RHS
At line 30259 BOUNDS
At line 34385 ENDATA
Problem MODEL has 2751 rows, 4125 columns and 12375 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Problem is infeasible - 0.01 seconds
Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.03   (Wallclock seconds):       0.05

Status: Infeasible
Objective Cost: $111,715,504.32
New Facilities to Build:

    zipcode  facility_type  num_to_build  slots_added  under5_slots_added
0     10026              3            13         5200                2600
1     10027              3            14         5600                2800
2     10501              3            17         6800                3400
3     10504              3            15         6000                3000
4     10505              3            22         8800                4400
5     10509              3            18         7200                3600
6     10510              3            20         8000                4000
7     10511              3            18         7200                3600
8     10518              3            19         7600                3800
9     10524              3            14         5600                2800
10    10526              3            21         8400                4200
11    10527              3            22         8800                4400
12    10533              3            17         6800                3400
13    10535              3            14         5600                2800
14    11040              3            25        10000                5000
15    11042              3            22         8800                4400
16    11209              3            28        11200                5600
17    11362              3            16         6400                3200
18    11363              3            13         5200                2600
19    11364              3            24         9600                4800
20    11365              3            15         6000                3000
21    11366              3            24         9600                4800
22    11367              3            21         8400                4200
23    11368              3            27        10800                5400
24    11369              3            13         5200                2600
25    11370              3            14         5600                2800
26    11372              3            16         6400                3200
27    11373              3            19         7600                3800
28    11374              3            16         6400                3200
29    11375              3            17         6800                3400
30    11377              3            19         7600                3800
31    11385              3            16         6400                3200
32    11411              3            40        16000                8000
33    11412              3            21         8400                4200
34    11413              3            15         6000                3000
35    11415              3            22         8800                4400
36    11418              3            18         7200                3600
37    11420              3            15         6000                3000
38    11421              3            26        10400                5200
39    11426              3            19         7600                3800
40    11427              3            15         6000                3000
41    11428              3            14         5600                2800
42    11429              3            21         8400                4200
43    11433              3            14         5600                2800
44    11435              3            15         6000                3000
45    11552              3            24         9600                4800
46    11559              3            14         5600                2800
47    11563              3            13         5200                2600
48    11568              3            18         7200                3600
49    11709              3            16         6400                3200
50    11768              3            17         6800                3400

In [33]:
expand_rows = []
for (a, j), var in x.items():
    if var.varValue and var.varValue > 0:
        original_capacity = next(nt for (fid, nt, _) in facilities[a] if fid == j)
        under5_capacity = next(nu for (fid, _, nu) in facilities[a] if fid == j)
        percent_increase = round(100 * var.varValue, 2)
        expand_rows.append({
            "zipcode": a,
            "facility_id": j,
            "expand_%": percent_increase,
            "added_slots": round(var.varValue * original_capacity),
            "under5_capacity_existing": under5_capacity,
        })

df_expansions = pd.DataFrame(expand_rows)
print("Facilities to Expand:")
display(df_expansions)

Facilities to Expand:

Empty DataFrame
Columns: []
Index: []

Our model suggests that for New York to eliminate all child care deserts while minimizing the cost, new facilities should be built rather than expanding existing ones.